apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: heytm27oz-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/heytm27oz-java-quarkus-gitops