apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: heytm27oz-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-61a817d86c.ezm0.p3.openshiftapps.com/rhtap/rhtap-qe:5ec40f6ce0987801433db2ac6beff19fa2a9ac4d@sha256:2d5ef7698909ba5c3c4a0092f6207f926313c02a80222022618390507e98fe5c
        name: container-image  
